Docs: 오류 수정5

diff --git a/.github/workflows/close-jira-issue.yml b/.github/workflows/close-jira-issue.yml
--- a/.github/workflows/close-jira-issue.yml
+++ b/.github/workflows/close-jira-issue.yml
@@ -21,15 +21,14 @@ jobs:
         id: extract-key
         run: |
           ISSUE_TITLE="${{ github.event.issue.title }}"
-
-          CLEANED_TITLE=$(echo "$ISSUE_TITLE" | sed 's/[–—−‑]/-/g')
+          CLEANED_TITLE=$(echo "$ISSUE_TITLE" | tr -d '[]')
           echo "🧼 Cleaned title: $CLEANED_TITLE"
 
           JIRA_KEY=$(echo "$CLEANED_TITLE" | grep -oE '[A-Z]+-[0-9]+')
 
           if [ -z "$JIRA_KEY" ]; then
-          echo "❌ JIRA key could not be extracted. Exiting."
-          exit 1
+            echo "❌ JIRA key could not be extracted. Exiting."
+            exit 1
           fi
 
           echo "✅ Extracted JIRA_KEY=$JIRA_KEY"
